// Code generated by protoc-gen-go.
// source: github.com/unravelin/proto3-utils/proto/null/null.proto
// DO NOT EDIT!

/*
Package null is a generated protocol buffer package.

It is generated from these files:
	github.com/unravelin/proto3-utils/proto/null/null.proto

It has these top-level messages:
	NullDouble
	NullFloat
	NullInt32
	NullInt64
	NullUint32
	NullUint64
	NullSint32
	NullSint64
	NullFixed32
	NullFixed64
	NullSfixed32
	NullSfixed64
	NullBool
	NullString
	NullBytes
*/
package null

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type NullDouble struct {
	Value float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	Set   bool    `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullDouble) Reset()         { *m = NullDouble{} }
func (m *NullDouble) String() string { return proto.CompactTextString(m) }
func (*NullDouble) ProtoMessage()    {}

type NullFloat struct {
	Value float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
	Set   bool    `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullFloat) Reset()         { *m = NullFloat{} }
func (m *NullFloat) String() string { return proto.CompactTextString(m) }
func (*NullFloat) ProtoMessage()    {}

type NullInt32 struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Set   bool  `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullInt32) Reset()         { *m = NullInt32{} }
func (m *NullInt32) String() string { return proto.CompactTextString(m) }
func (*NullInt32) ProtoMessage()    {}

type NullInt64 struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Set   bool  `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullInt64) Reset()         { *m = NullInt64{} }
func (m *NullInt64) String() string { return proto.CompactTextString(m) }
func (*NullInt64) ProtoMessage()    {}

type NullUint32 struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Set   bool   `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullUint32) Reset()         { *m = NullUint32{} }
func (m *NullUint32) String() string { return proto.CompactTextString(m) }
func (*NullUint32) ProtoMessage()    {}

type NullUint64 struct {
	Value uint64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Set   bool   `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullUint64) Reset()         { *m = NullUint64{} }
func (m *NullUint64) String() string { return proto.CompactTextString(m) }
func (*NullUint64) ProtoMessage()    {}

type NullSint32 struct {
	Value int32 `protobuf:"zigzag32,1,opt,name=value" json:"value,omitempty"`
	Set   bool  `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullSint32) Reset()         { *m = NullSint32{} }
func (m *NullSint32) String() string { return proto.CompactTextString(m) }
func (*NullSint32) ProtoMessage()    {}

type NullSint64 struct {
	Value int64 `protobuf:"zigzag64,1,opt,name=value" json:"value,omitempty"`
	Set   bool  `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullSint64) Reset()         { *m = NullSint64{} }
func (m *NullSint64) String() string { return proto.CompactTextString(m) }
func (*NullSint64) ProtoMessage()    {}

type NullFixed32 struct {
	Value uint32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
	Set   bool   `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullFixed32) Reset()         { *m = NullFixed32{} }
func (m *NullFixed32) String() string { return proto.CompactTextString(m) }
func (*NullFixed32) ProtoMessage()    {}

type NullFixed64 struct {
	Value uint64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	Set   bool   `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullFixed64) Reset()         { *m = NullFixed64{} }
func (m *NullFixed64) String() string { return proto.CompactTextString(m) }
func (*NullFixed64) ProtoMessage()    {}

type NullSfixed32 struct {
	Value int32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
	Set   bool  `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullSfixed32) Reset()         { *m = NullSfixed32{} }
func (m *NullSfixed32) String() string { return proto.CompactTextString(m) }
func (*NullSfixed32) ProtoMessage()    {}

type NullSfixed64 struct {
	Value int64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	Set   bool  `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullSfixed64) Reset()         { *m = NullSfixed64{} }
func (m *NullSfixed64) String() string { return proto.CompactTextString(m) }
func (*NullSfixed64) ProtoMessage()    {}

type NullBool struct {
	Value bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Set   bool `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullBool) Reset()         { *m = NullBool{} }
func (m *NullBool) String() string { return proto.CompactTextString(m) }
func (*NullBool) ProtoMessage()    {}

type NullString struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Set   bool   `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullString) Reset()         { *m = NullString{} }
func (m *NullString) String() string { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()    {}

type NullBytes struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Set   bool   `protobuf:"varint,2,opt,name=set" json:"set,omitempty"`
}

func (m *NullBytes) Reset()         { *m = NullBytes{} }
func (m *NullBytes) String() string { return proto.CompactTextString(m) }
func (*NullBytes) ProtoMessage()    {}

func init() {
}
